catalog/core/urls.py
from django.urls import path
from .views import PageListView

urlpatterns = [
    path('', PageListView.as_view(), name="home"),
]

catalog/cuber/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    #Path Core
    path('', include('core.urls')),

    #Path Admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/core/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Catalog(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    description = models.TextField(verbose_name="Descripción")
    claves = models.TextField(verbose_name="Palabras Claves")
    link = models.URLField(verbose_name="Dirección Web", null=True, blank=True)
    image = models.ImageField(verbose_name="Imagen", upload_to="img", null=True, blank=True)
    alert = models.TextField(verbose_name="Alerta", null=True, blank=True)
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Catalogo"
        verbose_name_plural = "Catalogos"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

catalog/core/views.py
from django.views.generic.list import ListView
from django.shortcuts import render
from .models import Catalog

# Create your views here.
class PageListView(ListView):
    model = Catalog

catalog/core/templates/core/Catalog_list.html
{% extends 'core/base.html' %}

{% block title %}Catalogo Enlaces{% endblock %}

{% block content %}
{% for Catalog in catalog_list %}
        <div class="col-3">
            <article class="margin-b-big stack__cards__card stack__cards__card-main">
                    <div class="bottom-portion text-center">
                        <img src="{{Catalog.image.url}}" class="img-fluid" alt="logo clínico">
                    </div>
                <div class="stack__cards__card__info">
                    <h5 class="margin-t-reset">
                        <a href="{{Catalog.link}}">{{Catalog.title}}</a>
                    </h5>
                        {% if Catalog.alert %}
                            <div class="alert alert-danger">{{Catalog.alert}}</div>
                        {% endif %}
                    <!---->
                    <p class="hide">
                        {{Catalog.claves}}
                    </p>
                </div>
                <div class="stack__cards__card__footer">
                        <span aria-hidden="true">
                        {{Catalog.description}}
                        </span>
                        <div class="btn-container">
                            <button type="button" class="btn btn-rounded btn-success" onClick="window.open('{{Catalog.link}}');">Iniciar</button>
                        </div>
                </div>
            </article>
        </div>
{% endfor %}
{% endblock %}

catalog/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta content="IE=edge" http-equiv="X-UA-Compatible">
		<meta content="width=device-width, initial-scale=1" name="viewport">

		{% load static %}
		<script src="{% static 'core/js/webfont.js' %}"></script>
		<script src="{% static 'core/js/iwb8jlp.js' %}"></script>


		<meta content="#00437B" name="theme-color">


		<link href="{% static 'core/css/hex.min.css' %}" rel="stylesheet">
		<link href="{% static 'core/css/styles.css' %}" rel="stylesheet">
		<title>
		Catalogo de Enlaces
		</title>

		
		<link href="{% static 'core/css/application-8e0d1e6fe93df07bde3b4448fc164e780806fc54f65941020c4f4332232d85eb.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body class="stacks-index  stacks index">
		<div>
			<div class="top-portion text-center">
				<img src="{% static 'core/img/logo_CESFAM_SIT.png' %}" class="img-fluid" alt="logo administrativo">
				<h3>Accede a una mejor experiencia para la APS Digital</h3>
			</div> 
		</div>
		<main>
			<div class="stack">
				<header class="container">
					<label for="stackSearch">
					<!--<h2>Buscar Enlaces</h2>-->
					</label>
				<input aria-controls="stacks" id="stackSearch" placeholder="Busqueda de Enlaces..." role="search" type="search">
				</header>

				<section>
					<div class="container stack__cards margin-v-giant padding-h-big">
						<div aria-live="polite" class="row collapse-3-b-desktop collapse-2-b-tablet collapse-b-phone-land" id="stacks" role="region">
							<div class="col-8 stack__cards__empty hide">
								<div class="type-bigger margin-t-normal text-c">
								No encontramos ningún enlace que coincida con tu búsqueda.
								</div>
							</div>
							<!--####INICIO BLOQUE####-->
							{% block content %}{% endblock %}
							
							<!--####FIN BLOQUE####-->
							
						</div>
					</div>
				</section>
				<hr class="separator separator-50 separator-small margin-v-bigger">
			</div>
		</main>


		<script crossorigin="anonymous" src="{% static 'core/js/bundle.min.js' %}"></script>
		<script src="{% static 'core/js/hex.min.js' %}"></script>
		<script src="{% static 'core/js/jquery.min.js' %}"></script>
		<!-- Javascript code to attach the google captcha verification event to the form -->
		<script>
		  function onloadRecaptcha() {
			$('.g-recaptcha').each(function(i) {
			  var $form = $(this).parents('form');
			  var id = $(this).attr('id');
			  var $button;
		  
			  // Render the recaptcha explicitly
			  grecaptcha.render(id, {
				'sitekey': '6LcVHTEUAAAAAKMMxsspBHmrR7bXkMnNT_jyEEMn',
				'callback': function(e) {
				  onSubmitForm('#' + id);
				},
				'badge': 'inline',
				'size': 'invisible'
			  });
		  
			  // Get the button
			  if ($form.find('input[type="submit"]').length > 0) {
				$button = $form.find('input[type="submit"]');
			  } else if ($form.find('button[type="submit"]').length > 0) {
				$button = $form.find('button[type="submit"]');
			  } else {
				$button = $form.find('button');
			  }
		  
			  // Subscribe to the event
			  $button.on('click', function(e) {
				if($form[0].checkValidity()) {
				  e.preventDefault();
				  // grecaptcha uses the rendering index as the identifier. We must use this
				  // this index to avoid execute wrong captcha validations
				  grecaptcha.execute(i);
				}
			  });
			});
		  };
		  
		  // Send the form
		  function onSubmitForm(id) {
			$(id).parents('form').submit();
		  }
		</script>


		<script src="{% static 'core/js/application-f676afece195309c87be56174f43495b5aa6beb2f7e3285b3a98fdbecf900f38.js' %}"></script>


	</body>
</html>